### ISSUE TITLE
Getting exception with latest selenium.

### ISSUE THREAD

**Issue by BugDiver** [getgauge/gauge-java#83]
### Expected behavior
Should be able to execute a gauge java project with latest version of selenium.

### Actual behavior
Doesn't work with selenium `3.3.0`.

### Steps to reproduce
1. create a `java_maven_selenium` project by running `gauge --init java_maven_selenium`.
2. Update `selenium` dependency to `3.3.1` in `pom.xml`.
3. run the project.

## Stacktrace
```
Error Message: java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)V
  Stacktrace:
  org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:111)
  org.openqa.selenium.chrome.ChromeDriverService.access$000(ChromeDriverService.java:32)
  org.openqa.selenium.chrome.ChromeDriverService$Builder.findDefaultExecutable(ChromeDriverService.java:137)
  org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:302)
  org.openqa.selenium.chrome.ChromeDriverService.createDefaultService(ChromeDriverService.java:88)
  org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:124)
  driver.DriverFactory.getDriver(DriverFactory.java:21)
  driver.Driver.initializeDriver(Driver.java:16)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  com.thoughtworks.gauge.execution.MethodExecutor.execute(MethodExecutor.java:38)
  com.thoughtworks.gauge.execution.HooksExecutor$TaggedHookExecutor.executeHook(HooksExecutor.java:102)
  com.thoughtworks.gauge.execution.HooksExecutor$TaggedHookExecutor.execute(HooksExecutor.java:88)
  com.thoughtworks.gauge.execution.HooksExecutor.execute(HooksExecutor.java:45)
  com.thoughtworks.gauge.processor.MethodExecutionMessageProcessor.executeHooks(MethodExecutionMessageProcessor.java:65)
  com.thoughtworks.gauge.processor.SuiteExecutionStartingProcessor.process(SuiteExecutionStartingProcessor.java:32)
  com.thoughtworks.gauge.connection.MessageDispatcher.dispatchMessages(MessageDispatcher.java:89)
  com.thoughtworks.gauge.GaugeRuntime.dispatchMessages(GaugeRuntime.java:105)
  com.thoughtworks.gauge.GaugeRuntime.access$100(GaugeRuntime.java:37)
  com.thoughtworks.gauge.GaugeRuntime$2.run(GaugeRuntime.java:86)
  java.lang.Thread.run(Thread.java:745)
```

### Gauge version
```
Gauge version: 0.8.2.36e1690-master

Plugins
-------
java (0.6.2)
```

**Comment by smathistad** [comment]
The latest version of selenium uses guava version 21.  It appears that gauge-java is still using guava version 15, which is from Sep 6, 2013 (3 and a half years old).

**Comment by kashishm** [comment]
Adding the following dependency in project's `pom.xml` file will solve the issue.
```
<dependency>
    <groupId>com.google.guava</groupId>
    <artifactId>guava</artifactId>
    <version>21.0</version>
</dependency>
```
@smathistad gauge-java has a dependency on `org.reflections:reflections` which internally has a dependency on `guava`. We have updated the `reflection` library to the latest version 0.9.11 which has `guava` 20.0 as a dependency. We should make sure that we are always using the latest versions.

**Comment by Thunderforge** [comment]
This issue should be fixed with #86, although any projects should still declare Guava on their own, rather than relying on the version of Guava transitively pulled in by Gauge.

**Comment by Apoorva-GA** [comment]
Issue is fixed. @sguptatw please have a look and let us know if issue still persist.

**Comment by AnandChaurasia** [comment]
I am getting this Issue when launching IE, 
java.lang.AbstractMethodError: org.openqa.selenium.ImmutableCapabilities.is(Ljava/lang/String;)Z
and In case of chrome:
java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)V

here is my maven dependencies. 
 <dependency>
      <groupId>org.seleniumhq.selenium</groupId>
      <artifactId>selenium-java</artifactId>
      <version>3.8.1</version>
    </dependency>
    <dependency>
      <groupId>org.seleniumhq.selenium</groupId>
      <artifactId>selenium-firefox-driver</artifactId>
      <version>3.8.1</version>
    </dependency>

    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <version>21.0</version>
    </dependency>

    
    <dependency>
      <groupId>org.seleniumhq.selenium</groupId>
      <artifactId>selenium-server</artifactId>
      <version>3.8.1</version>
    </dependency>
